---
- hosts: all
  become: true
  vars:
    user: "mario"
    env: "sviluppo"

    whitelist:
      - pippo
      - paperino
      - topolino

    base_image: "python:3.9-slim"
    app_port: 5000

  tasks:
    - name: Genera il file limits.conf con il template Jinja
      ansible.builtin.template:
        src: templates/limits.j2
        dest: /tmp/limits.txt

    - name: Aggiungi impostazioni a /etc/security/limits.txt
      ansible.builtin.blockinfile:
        path: /etc/security/limits.conf
        block: "{{ lookup('ansible.builtin.file', '/tmp/limits.conf') }}"
        insertafter: EOF
        create: yes


    - name: Aggiungi whitelist a /etc/security/access.conf
      ansible.builtin.blockinfile:
        path: /etc/security/access.conf
        block: |
          {% for user in whitelist %}
          + : {{ user }} : ALL
          {% endfor %}
        insertbefore: "- : ALL : ALL"
        create: yes

    - name: Genera il Dockerfile dinamico
      ansible.builtin.template:
        src: templates/Dockerfile.j2
        dest: /home/vagrant/Dockerfile

