Vagrant.configure("2") do |config|
  config.vm.hostname = "Franco"
  config.vm.box = "rockylinux/9"
  config.vbguest.auto_update = false
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
